### PR TITLE
Completed JavaScript restaurant page project

### PR DESCRIPTION
**Pull request by RyelBanfield**
This PR contains the completed JS restaurant page project. It was built entirely using JavaScript to generate the content.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Invalid submission :warning:
**Hello Ryel Banfield** 
Make sure all your linter checks are successful.
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by RyelBanfield** [comment]
@andresporras3423 The failing linter is not required by microverse submissions and the passing of it will cause ESLint (which is required) to fail. Please check these things before you mark a submission invalid.

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hello @RyelBanfield, 

**You have done a commendable job in this project and it should be approved :muscle:**

However, there are minor touches to be done just to ensure that everything is right.

### To improve
- [x] For the run commands inside the `script` kindly set the `mode` option to `development` or `production` to enable defaults for each environment. Below is an example :arrow_down:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

### Optional
- [ ] Since you have the run commands, the appropriate way to start the app in development would be to run `npm start` in the terminal. Kindly update this in the readme's `getting started` sections, since not everyone uses vscode.

**Kindly make the above changes and ask for another review**

Feel free to reach me on slack or leave a comment while mentioning me and I will  be happy to respond

_Slack: Oloo Moses_

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
